version: '3'
services: 
  mongo: 
    container_name: mongo
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - "./data:/data/db"
      - ./mongod.conf:/etc/mongod.conf
  
  nodejs: 
    build: .
    container_name: dockerised-nodejs
    environment:
      - DB_HOST=mongodb://mongo:27017/posts
    links: 
      - mongo
    ports: 
      - "3000:3000"
    #command: node seeds/seed.js

